### ISSUE TITLE
Ошибка     raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by MandarinAxle** [no-comm/standoff-2-API#1]
Привет, решил использовать твой скрипт для одного дела.Думал,что сейчас все будет супер и все будет работать,но столкнулся с проблемой.

Я скопировал твой код из README.MD:
```
import main
pr = main.account(42073869)
print(pr)
#output
#('kexswt_', 'https://avatars-19e92.kxcdn.com/48c416cd-3fdc-47fe-b302-bcac3f78dd00')
main.avatar(pr[1])
#and create gg.webp
```
В main.py я ничего не менял.

Мне выдает ошибку -    ``` raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) ```

Если сможешь помочь,буду благодарен!

**Comment by no-comm** [comment]
Прошу прощения за долгий ответ, но standoff обновили свой сайт и я попытался обновить код и у меня не получилось. обновления не будет

**Comment by no-comm** [comment]
Прошу прощения за долгий ответ, но standoff обновили свой сайт и я переписал код на selenium но работа программы увеличилась

**Comment by no-comm** [comment]
напиши если помогло

**Comment by MandarinAxle** [comment]
> напиши если помогло

Привет,завтра отпишу.

**Comment by MandarinAxle** [comment]
> Прошу прощения за долгий ответ, но standoff обновили свой сайт и я переписал код на selenium но работа программы увеличилась 

Я писал похожий код.Получение аватарки и ника занимало +-15 минут на моем компьютере и +-8 секунд на сервере.

**Comment by MandarinAxle** [comment]
> напиши если помогло

Привет,все работает.Спасибо!
