### ISSUE TITLE
code is overcomplicated

### ISSUE THREAD

**Issue by ayxkaddd** [no-comm/standoff-2-API#2]
you could use just requests lib by accessing this url - `https://store.standoff2.com/api/v1/accounts/<id>`

**Comment by no-comm** [comment]
yes, and what do you suggest?

**Comment by no-comm** [comment]
I did not manage to do this because before the code was on Requests But it stopped working and had to be rewritten to Selenium
https://github.com/no-comm/standoff-2-API/issues/1

**Comment by no-comm** [comment]
Made the code easier
