### ISSUE TITLE
Response [400]

### ISSUE THREAD

**Issue by MandarinAxle** [no-comm/standoff-2-API#3]
Привет! Твой код работал хорошо до сегодняшнего дня.

Однако, при использовании кода из примера, получен следующий результат: 
`raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
`<Response [400]>`

**Comment by no-comm** [comment]
rewritten in playwright
